### ISSUE TITLE
Revisit suggestion logic

### ISSUE THREAD

**Issue by maryldyer** [srosro/deepspring-shellmate#100]

**Comment by srosro** [comment]
* When do we kickoff a "set" of suggestions
* What is the criteria for generating additional suggestions?
* Can allow the user to request additional suggestions (e.g. if shellmate gets the "intent" right but the suggestion is wrong)?

**Comment by srosro** [comment]
Also, see this user feedback:

<img width="692" alt="Screenshot 2024-08-16 at 10 29 55 AM" src="https://github.com/user-attachments/assets/fd286346-e874-425b-95ab-2f9c3ca91b4c">

**Comment by srosro** [comment]
Next step is for either @plonkus or @delattre1 to review user feedback above and propose changes to the current suggestion logic.

**Comment by plonkus** [comment]
Will chat with @maryldyer about possible solutions before estimating fix

**Comment by delattre1** [comment]
- Increased the debouncer threshold from 1s -> 1.5s 
- Logic to store new terminal state as pending (if previous state is still being processed)
- Logic to avoid thread errors

**Comment by delattre1** [comment]
Also the user already has the ability to pause the suggestions
