### ISSUE TITLE
"API key is invalid" error message at startup

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#110]
<img width="502" alt="Screenshot 2024-08-14 at 9 44 06 PM" src="https://github.com/user-attachments/assets/0e87cc18-c6c1-44a7-852c-8f65461db384">

**Comment by srosro** [comment]
@delattre1 is there analytics we can add that can track how often this occurs? Ideally also track what the HTTP response is from OpenAI?

**Comment by plonkus** [comment]
Merging with #133
