### ISSUE TITLE
More analytics events

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#111]
Get "auto update" prompt
Enable auto update
Onbaording
Step 1 of onboarding flow shown
Step 1 of onboarding flow completed
Step 2 of onboarding flow shown
Step 2 of onboarding flow completed
Step 3 of onboarding flow shown
Step 3 of onboarding flow completed
Onboarding modal closed
users that get "invalid API key" error,
users that open settings window
launch at login enabled
launch at login disabled
auto-open w/ terminal enabled
auto-open w/ terminal disabled
users that add their own api key (daniel note: only when validated)
getting a terminal suggestion "group" (e.g. black bar has rendered)
injecting a terminal suggestion (sm)
copying sm command

**Comment by srosro** [comment]
On my to validate - so far I don't see any of these in Mixpanel.

**Comment by srosro** [comment]
@delattre1 are we tracking "Step 1 of onboarding flow shown"

**Comment by delattre1** [comment]
This is the current state of these events:
### Done:

- **Onboarding:**
  - Step 1 of onboarding flow completed
  - Step 2 of onboarding flow shown
  - Step 2 of onboarding flow completed
  - Step 3 of onboarding flow shown
  - Step 3 of onboarding flow completed
  - Onboarding modal closed

- **Users that open settings window:**
  - Auto-open w/ terminal enabled
  - Auto-open w/ terminal disabled

- **Injecting a terminal suggestion (`sm`):**
  - Copying `sm` command
  - Users that add their own API key *(Daniel note: only when validated)*

### Todo:

- **Get "auto update" prompt**
- **Enable auto update**
- **Users that get "invalid API key" error**
- **Getting a terminal suggestion "group"** (e.g., black bar has rendered)

- **Onboarding:**
  - Step 1 of onboarding flow shown

- **Users that open settings window:**
  - Launch at login enabled
  - Launch at login disabled

**Comment by plonkus** [comment]
Research updating SDK for:
* Get "auto update" prompt
* Enable auto update

Remaining ones:
* Users that get "invalid API key" error
* Getting a terminal suggestion "group" (e.g., black bar has rendered)
* Onboarding: Step 1 of onboarding flow shown
* Users that open settings window: 
  * Launch at login enabled
  * Launch at login disabled

**Comment by delattre1** [comment]
Confirmed we can't get the event for the `Launch at login ` as the package that takes care of that has the observer as private. would require more effort to do that...

**Comment by delattre1** [comment]
Added sparkle events:
(updater)
![image](https://github.com/user-attachments/assets/8a9f27c7-1c9f-40d3-92e3-4fdc86b07193)

**Comment by delattre1** [comment]
![image](https://github.com/user-attachments/assets/95b56643-445d-4587-bc59-d9b3d6e889ba)

**Comment by delattre1** [comment]
![image](https://github.com/user-attachments/assets/8e5c8005-6fea-4038-a6d5-c34cc056d320)
