### ISSUE TITLE
User feedback: "sm x" command not working

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#112]
Next step - suggest question I can ask the user to debug.

<img width="689" alt="Screenshot 2024-08-16 at 7 42 37 AM" src="https://github.com/user-attachments/assets/e81fdfd5-0fe8-49ce-a394-3b107726a8f8">

**Comment by delattre1** [comment]
Closing this, as aside from the pause feature, the rest of the user feedback is similar to what’s covered in issue #100
