### ISSUE TITLE
Setting to pause suggestions

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#113]
User should be able disable certain tabs.  See this feedback:

<img width="692" alt="Screenshot 2024-08-16 at 8 07 36 AM" src="https://github.com/user-attachments/assets/3d02dd0a-7edc-4d9b-b16c-b8234ca384b0">

**Comment by maryldyer** [comment]
Based on feedback, we are seeing that users want to be able to:
1. Pause shellmate on specific tabs 
2. Pause shellmate when it's generating suggestions during inactivity
3. Pause shellmate when they don't need help


Solution:
- Add a pause/play button to the footer next to the generating suggestions indicator. 
- When a user hits `pause`, the icon changes to `play` and the "generating suggestions" text should change to "ShellMate paused" so it is clear why ShellMate isn't responding. 
- Hid the "No changes on Terminal"/"Detecting changes" text when ShellMate is paused
- When paused, stop tracking changes in the terminal and sending prompts to GPT

[**Figma link**](https://www.figma.com/design/cY3HB9J6jQROjDX7V9gqo8/shellmate?node-id=1481-7758&t=SO6gUla9gI9CCCUR-11)

<img width="2241" alt="Screenshot 2024-08-21 at 9 13 41 AM" src="https://github.com/user-attachments/assets/7e0eb6fe-a265-407d-9c08-6d7664612ed2">

**Comment by srosro** [comment]
Looks great!
