### ISSUE TITLE
What's the right "fresh" user experience when there's not enough context?

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#115]
What's the right "fresh" user experience when there's not enough context.  Options:
* Display nothing
* Display some sort of hint that helps the user understand what they could do when no suggestions exist.
* Display previous suggestions or the user's most common suggestions

Currently this is the UX:
![screenshot_2024-08-16_at_11 21 05___am](https://github.com/user-attachments/assets/e5f9dcbb-179a-49e9-95a0-da357ca7c30d)

**Comment by maryldyer** [comment]
Add an empty state message to ShellMate. This would be anytime a new ShellMate window is opened, before any suggestions have been generated. We have ~7 quotes that should rotate through displaying when a new window is opened.

We should make sure we are not generating the "request for relevant info" suggestion until we know the user is using the terminal. 

![image](https://github.com/user-attachments/assets/dab39d1b-ad5f-407b-96e6-4243dd2352cc)

[Copy Ideas](https://paper.dropbox.com/doc/Blank-suggestions--CVCXqm4tvvsXB96UpVZrkAFIAQ-RV3Xpd4j3kuA34ygkq4fv)
[Figma link](https://www.figma.com/design/cY3HB9J6jQROjDX7V9gqo8/shellmate?node-id=1239-22450&t=2zzpX4pjMmK0KlvO-11)

**Comment by delattre1** [comment]
![image](https://github.com/user-attachments/assets/62304dc1-8dab-454a-8503-19c695f92fb0)
![image](https://github.com/user-attachments/assets/3002cb2a-daca-461d-98e4-cef3e03ee40e)

**Comment by delattre1** [comment]
![image](https://github.com/user-attachments/assets/8348acb6-cbba-4eb2-9cce-5f1cac28078a)

Done:

1. Implement initial design
2. Add the Status bar on bottom of empty view as well

Todo:

1. Implement the other design (the one when there's no command. Instead it is a message
2. Block: What is the logic to rotate the suggestions? (e.g once a new terminal is opened would we want to show a random one BUT then would we want to show another one after some seconds? Or be fixed? And only select other one on app refreshes?

**Comment by delattre1** [comment]
https://github.com/user-attachments/assets/79c578f7-cfff-4a9e-85e9-2b3b2adeee5e
