### ISSUE TITLE
Warn user when sm CLI is not installed

### ISSUE THREAD

**Issue by delattre1** [srosro/deepspring-shellmate#117]
Implement a user experience enhancement to handle cases where the user tries to run the sm command in the CLI, but the terminal session was opened before ShellMate was installed.

Options:

- Notify the user to open a new terminal session for the command to work.
- Provide a suggestion that the user can copy and paste into their terminal to make the sm command available immediately.

**Comment by maryldyer** [comment]
On Shellmate's first open we open a new terminal window that way the user can see the walkthrough tips and experience shellmate working properly. If they switch back to a previously open window (I'm making an assumption that we would not know right away that we are going to have a problem) the ux follows the happy path until the user tries to execute a sm command and they get an error. Which is when we would have a special alert banner explaining that we encountered an issue.

I'm open to changing the alert copy if you have a better suggestion!

[Figma](https://www.figma.com/design/cY3HB9J6jQROjDX7V9gqo8/shellmate?node-id=1347-20394&t=qylqxtrJMDbgc8Xl-11)

<img width="2443" alt="Screenshot 2024-08-19 at 1 39 03 PM" src="https://github.com/user-attachments/assets/f50f9e43-2330-4c7d-bd38-92d4e909dfa4">

**Comment by delattre1** [comment]
A follow-up fix if put more time into development would be: Show a warning with the `source ~/.zshrc` or `source ~/.bashrc` command so the user can manually update their profile.

**Comment by delattre1** [comment]
When the user runs the command `sm 'how can I display a calendar'` in the terminal, it triggers both the `sm not installed` warning and the `pro tip: insert suggestion` instruction. This overlap causes a conflict in the user experience, where both states are activated simultaneously, potentially confusing the user.

![image](https://github.com/user-attachments/assets/c112462f-6d55-489b-8bd2-63e7c2262253)

**Comment by delattre1** [comment]
These are all the warnings implemented in the app:
![image](https://github.com/user-attachments/assets/c3fda279-e576-461d-a22b-ed5314d63b92)
![image](https://github.com/user-attachments/assets/887edccc-b344-4f7b-b16f-b89961d22af5)

**Comment by delattre1** [comment]
New bugs to fix:

Red warning should only show at the terminal window that has the problem. Not at all windows:
![image](https://github.com/user-attachments/assets/8ed5ded5-fa4d-4a1a-bc3a-a521e4c7ea21)

Fix padding between 1st pro-tip and the second element when red warning is showing will display without any padding

![image](https://github.com/user-attachments/assets/a3ebb6a8-ce1d-4c4b-979f-b90338b969ac)
