### ISSUE TITLE
Add Rotating Empty State Messages to ShellMate

### ISSUE THREAD

**Issue by delattre1** [srosro/deepspring-shellmate#125]
Mary's text about it:

> Sam and I had some fun with this but we want to add an empty state message to ShellMate. This would be anytime a new ShellMate window is opened, before any suggestions have been generated.
> We came up with some funny/entertaining quotes that highlight creative ways to use terminal and shellmate. Each time shellmate is re-opened we'd rotate through these quotes
> [You can contribute here ](https://paper.dropbox.com/doc/Blank-suggestions--CVCXqm4tvvsXB96UpVZrkAFIAQ-RV3Xpd4j3kuA34ygkq4fv):sweat_smile:

**Comment by maryldyer** [comment]
FYI - this is the same ticket as #115

**Comment by delattre1** [comment]
Closing duplicate
