### ISSUE TITLE
Add a "chat with the makers of shellmate" message in Shellmate

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#127]
We should schedule a time when we are in a hangout and users can jump in (directly from the app).  This would be a great way to get exposure to live users.  While right now we'll only show this at a set time/date, in the future - we might do this programmatically ("_Any time one of us is in a pre-set 'user feedback' google hangout, display a 'chat with the makers of shellmate' message_")

I imagine this might be a particular time the day / day after our 1.0 release.

Passing to @maryldyer for design.

**Comment by maryldyer** [comment]
"Chat with the Makers" banner is sticky to the top of the window and will appear whenever there is a live session. The `Join` button should open the call window in the users browser. `X` dismisses the banner

[**Figma link**](https://www.figma.com/design/cY3HB9J6jQROjDX7V9gqo8/shellmate?node-id=1414-34862&t=qylqxtrJMDbgc8Xl-11)

<img width="793" alt="Screenshot 2024-08-20 at 2 20 52 PM" src="https://github.com/user-attachments/assets/47653212-ada3-483c-95f3-efd807e896d1">

**Comment by delattre1** [comment]
https://github.com/user-attachments/assets/baac506f-ffd5-451f-b67b-4c1d596595a2

**Comment by delattre1** [comment]
The next step is to define the dates, hours, and meeting link that need to be added to the app before launch

**Comment by delattre1** [comment]
> Looks great 
> [@Daniel Delattre](https://deepspring-ai.slack.com/team/U072XVC9Q4B)
> .
> I'm not seeing a clear "time of day" trend in usage, so let's do a 30-minute session at 10AM-10:30AM and another one at 4-4:30PM the week after we launch. Let's hold both sessions for three days (M, W, F) and see if anyone attends.

**Comment by delattre1** [comment]
Removed the functionality for now. As discussed with Mary.
