### ISSUE TITLE
New Walkthrough UI - Part 2

### ISSUE THREAD

**Issue by delattre1** [srosro/deepspring-shellmate#129]
![image](https://github.com/user-attachments/assets/e0578b6a-8925-40b2-b2c0-b3fa64cb6445)

> Tip shows first time a user is presented with a wall of text with an error in it

### Description:
This issue is a continuation of issue #120 and focuses on refining the walkthrough UI when a user is first presented with a wall of text containing an error.

To correctly identify when this tip should be shown, further changes in the code are necessary. Potential solutions include:

- **Asking GPT** to identify an error situation dynamically. (Higher complexity)
- **Implementing a keyword check** for "error" or similar terms to trigger the tip. (Moderate complexity)
- **Developing a heuristic** to display the tip, e.g., after 20 free tier requests? (Low complexity)

**Comment by delattre1** [comment]
Mary's comment about it:

> That highlighting when we see an error tip was originally one of sam's ideas so he may have thoughts on how to best trigger it
> based on the ticket I feel like the second choice (moderate complexity) might be the best option

**Comment by srosro** [comment]
> Implementing a keyword check for "error" or similar terms to trigger the tip. (Moderate complexity)

Sounds great!  Maybe a basic heuristic like:


1. Kewords = "Error" or "Traceback" or "Exception"
2. Keyword found in text (case insensitive)
3. Suggestions don't have the words "fix" or any of the keywords in them?

**Comment by delattre1** [comment]
#120 and #129 demonstration


https://github.com/user-attachments/assets/2dd89b66-522d-4061-8cbe-7610a0edaff4
