### ISSUE TITLE
Layout bug ("No changes in Terminal")

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#130]
User reported - not sure why it's happening.  See "No changes on Terminal"

![d47c8d62-24ff-4cde-b970-40e18c6b5a67](https://github.com/user-attachments/assets/c0cae619-3bf6-4f9d-83d2-644af72f3538)

appBuildNumber: 0.9
appVersionString: 0.9
hardwareUUID: F50EEDFE-FFFA-5D8A-90A2-CC68EEB39003
manufacturer: Apple
memory: 24 GB
modelIdentifier: arm64
modelName: Mac14,2
mpLib: swift
os: macOS
osVersion: Version 14.0 (Build 23A344)
screenHeight: 956
screenWidth: 1470
serialNumber: G61DQVMV04
systemFirmwareVersion: Apple M2
totalNumberOfCores: 8

**Comment by srosro** [comment]
Marking this as low-ish priority.  It would be great to get this in the v1.0 release - but not required.

**Comment by plonkus** [comment]
Not sure how to reproduce this -- will timebox it to .5 to try to reproduce

**Comment by delattre1** [comment]
I tried to reproduce the issue but couldn't. Closing it
