### ISSUE TITLE
Make error messaging consistent & add retry logic

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#133]
These two errors appeared at the same time, but they say different things:
![Screenshot 2024-08-20 at 8 46 57 AM](https://github.com/user-attachments/assets/7dcd0bea-06e6-48ae-97a8-6aefd760cd59)
![Screenshot 2024-08-20 at 8 46 52 AM](https://github.com/user-attachments/assets/4c35f92d-37c6-4e89-9fa7-8e50793e8740)

Sounds like this was an intermittent network issue from OpenAI:
<img width="428" alt="Screenshot 2024-08-20 at 9 05 39 AM" src="https://github.com/user-attachments/assets/1022eb08-56ae-475b-ab33-fe97f2257f52">

We should probably have different error messaging for network issues vs explicit OpenAI API responses that the API key is invalid.

**Comment by plonkus** [comment]
Also research/fix issues with inputting api key in the settings:
* properly shows label of when it's not valid
* not allowing new lines in input
* ensure app always uses key that is provided
