### ISSUE TITLE
Change payment copy

### ISSUE THREAD

**Issue by srosro** [srosro/deepspring-shellmate#134]

**Comment by maryldyer** [comment]
[Figma](https://www.figma.com/design/cY3HB9J6jQROjDX7V9gqo8/shellmate?node-id=1377-30464&t=qylqxtrJMDbgc8Xl-11)

<img width="483" alt="Screenshot 2024-08-20 at 10 13 26 AM" src="https://github.com/user-attachments/assets/144462e4-7cfd-4aea-839a-ef3ec80676f1">
