### ISSUE TITLE
Move notification banner to the bottom of the window

### ISSUE THREAD

**Issue by maryldyer** [srosro/deepspring-shellmate#144]
We should display all notification banners (alerts or live chat) at the bottom of the ShellMate window. 

<img width="510" alt="Screenshot 2024-08-29 at 10 09 11 AM" src="https://github.com/user-attachments/assets/426bda3b-1ae1-457e-a82b-cadc42c325e4">

**Comment by delattre1** [comment]
https://github.com/user-attachments/assets/45fdafca-49f3-47ef-bf24-76d50ca42219
