### ISSUE TITLE
Helper banner for NUX integrated into history (also the UX for help text / errors)

### ISSUE THREAD

**Issue by maryldyer** [srosro/deepspring-shellmate#86]
Display a "help-banner" the first time a user is presented with a wall of text with an error in it:
> Did you know you can highlight a word or phrase to focus Shellmate's attention? Try it now by highlighting the error you're seeing.

<img width="1363" alt="Screenshot 2024-07-08 at 1 36 26 PM" src="https://github.com/srosro/shellbuddy/assets/2219891/6f2dc369-7e22-4957-a606-2ff3e4b82cc2">

This banner appears in the log of suggestions and behaves like other suggestion blocks.. it remains after new suggestions are added after it.

<img width="1300" alt="Screenshot 2024-07-08 at 1 43 03 PM" src="https://github.com/srosro/shellbuddy/assets/2219891/1436aa55-550a-49c0-921a-ac8f59769d9d">

**Comment by srosro** [comment]
@maryldyer I love this UX for the walkthrough.  It could also help with the vertical sizing of the screen (since 40% of users don't dismiss the walkthrough modal).  I could imagine this UX above being fine if it never gets dismissed (e.g., it just scrolls up into the history).  What do you think?
